spring:
    application:
        name: notification

    data:
        mongodb:
            uri: mongodb://localhost:27017/notification_db

    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: notification-service-group
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: "*"
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME:}
        password: ${MAIL_PASSWORD:}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

server:
    port: 8085
