spring:
    application:
        name: student

    datasource:
        url: jdbc:postgresql://localhost:5432/student_db
        username: student_user
        password: testSecret!
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true

    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.xml

docker:
    compose:
        enabled: true
        file: ./docker-compose.yml
        wait-for-services: true