spring:
    application:
        name: student

    datasource:
        url: jdbc:postgresql://localhost:5432/student_db
        username: student_user
        password: testSecret!
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true

    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.xml

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8090/realms/diploma-realm
                    jwk-set-uri: http://localhost:8090/realms/diploma-realm/protocol/openid-connect/certs

    grpc:
        server:
            port: 9081

springdoc:
  api-docs:
    path: /student-openapi/v3/api-docs
    resolve-server-url: true

keycloak:
  auth-server-url: http://localhost:8090
  realm: diploma-realm
  admin:
    username: ${KEYCLOAK_ADMIN:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
    client-id: admin-cli

server:
  port: 8081
  forward-headers-strategy: framework