spring.application.name=student

spring.datasource.url=jdbc:postgresql://localhost:5432/student_db
spring.datasource.username=student_user
spring.datasource.password=testSecret!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

server.port=8080