spring:
    application:
        name: risk-prediction

    datasource:
        url: jdbc:postgresql://localhost:5432/risk_db
        username: risk_user
        password: testSecret!
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true

    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.xml

    data:
        mongodb:
            uri: mongodb://localhost:27017/risk_history_db

    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: risk-prediction-service-group
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: "*"
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    grpc:
        client:
            attendance-service:
                address: 'static://localhost:8082'
            grade-service:
                address: 'static://localhost:8083'

server:
    port: 8084
